version: "2"
run:
  concurrency: 4
  go: "1.23"
  modules-download-mode: readonly
  issues-exit-code: 2
  tests: true
  allow-parallel-runners: false
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - decorder
    # - depguard
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - ireturn
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - predeclared
    - promlinter
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - regexpMust
        - commentedOutCode
        - docStub
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      settings:
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: false
        hugeParam:
          sizeThreshold: 64
        nestingReduce:
          bodyWidth: 4
        rangeValCopy:
          sizeThreshold: 64
          skipTestFuncs: false
        tooManyResultsChecker:
          maxResults: 100
        truncateCmp:
          skipArchDependent: false
        underef:
          skipRecvDeref: false
        unnamedResult:
          checkExported: true
    gocyclo:
      min-complexity: 18
    gosec:
      excludes:
        - G404
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
